export const getLanguageCode = (language: string): string => {
  const map: Record<string, string> = {
    'English': 'gb',
    'Arabic': 'sa',
    'Bulgarian': 'bg',
    'Chinese': 'cn',
    'Chinese (Simplified)': 'cn',
    'Chinese (Traditional)': 'cn',
    'Simplified Chinese': 'cn',
    'Traditional Chinese': 'cn',
    'Czech': 'cz',
    'Danish': 'da',
    'Dutch': 'nl',
    'Finnish': 'fi',
    'French': 'fr',
    'German': 'de',
    'Greek': 'gr',
    'Hungarian': 'hu',
    'Indonesian': 'id',
    'Italian': 'it',
    'Japanese': 'jp',
    'Korean': 'kr',
    'Norwegian': 'no',
    'Polish': 'pl',
    'Portuguese': 'pt',
    'Portuguese - Portugal': 'pt',
    'Portuguese-Brazil': 'pt-BR',
    'Portuguese - Brazil': 'pt',
    'Romanian': 'ro',
    'Russian': 'ru',
    'Spanish - Spain': 'es',
    'Spanish-Latin America': 'es',
    'Spanish - Latin America': 'es',
    'Swedish': 'sv',
    'Thai': 'th',
    'Turkish': 'tr',
    'Ukrainian': 'ua',
    'Vietnamese': 'vi',
  }

  return map[language] ?? null
}
